name: edbuddy
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  
  url_launcher: ^6.1.5
  internet_connection_checker: ^0.0.1+4
  firebase_core: ^1.21.0
  firebase_storage: ^10.3.5
  rflutter_alert: ^2.0.4
  google_fonts: ^3.0.1
  dynamic_height_grid_view: ^0.0.3
  line_awesome_flutter: ^2.0.0
  fluttertoast: ^8.0.9
  dropdown_search: ^5.0.2
  image_picker: ^0.8.5+3

  google_nav_bar: ^5.0.6
  shrink_sidemenu: ^2.0.0+2-null-safety
  font_awesome_flutter: ^10.1.0
  getwidget: ^3.0.1
  firebase_auth: ^3.6.4
  filter_list: ^1.0.2
  cloud_firestore: ^3.4.5


flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/fonts/